---
 - name: webserver -> Create webserver Security Group
   local_action:
     module: ec2_group
     name: "{{ item.sg_name }}"
     description: "{{ item.sg_description }}"
     region: "{{ vpc_region }}" 
     vpc_id: "{{ vpc.vpc_id }}" 
     state: present
     rules: "{{ item.sg_rules }}"
     rules_egress: "{{ item.sg_rules_egress }}"
   with_items: webserver_security_groups
   register: webserver_sg

 - name: webserver -> Tag the sg
   local_action:
     module: ec2_tag
     resource: "{{ item.group_id}}"
     region: "{{ vpc_region }}"
     state: present
     tags:
       Name: "{{ vpc_name }}-{{ item.item.sg_name }}"
   with_items: webserver_sg.results